{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "n0rCN8JWSa9a"
      },
      "outputs": [],
      "source": [
        "!pip install torch\n",
        "!pip install opencv-python\n",
        "!pip install pandas\n",
        "!pip install ultralytics"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import cv2\n",
        "import torch\n",
        "import pandas as pd\n",
        "from google.colab.patches import cv2_imshow\n",
        "import datetime\n",
        "\n",
        "# Define o caminho para o arquivo de vídeo\n",
        "# Certifique-se de que o nome e a pasta estejam corretos no seu ambiente do Colab\n",
        "video_path = \"/content/video_sprint3.mp4\"\n",
        "\n",
        "# Lista para armazenar o log de detecções\n",
        "# Cada entrada na lista será um dicionário com os dados de um frame\n",
        "detections_log = []\n",
        "\n",
        "# Define o tempo de início e fim para o processamento do vídeo, em segundos\n",
        "start_time_sec = 6\n",
        "end_time_sec = 9\n",
        "\n",
        "# Carrega o modelo YOLOv5 pré-treinado da biblioteca 'ultralytics'\n",
        "# O 'yolov5s' é a versão menor e mais rápida do modelo\n",
        "model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True)\n",
        "# Configura o modelo para detectar apenas a classe 'moto', que tem o ID 3\n",
        "model.classes = [3]\n",
        "\n",
        "# Inicializa a captura de vídeo a partir do arquivo\n",
        "cap = cv2.VideoCapture(video_path)\n",
        "\n",
        "# Verifica se o arquivo de vídeo foi aberto corretamente\n",
        "if not cap.isOpened():\n",
        "    print(f\"Erro: Não foi possível abrir o arquivo de vídeo em {video_path}\")\n",
        "else:\n",
        "    # --- Configuração do Ponto de Partida e Fim do Vídeo ---\n",
        "    # Converte o tempo de início de segundos para milissegundos\n",
        "    start_time_ms = start_time_sec * 1000\n",
        "    # Define a posição inicial do vídeo\n",
        "    cap.set(cv2.CAP_PROP_POS_MSEC, start_time_ms)\n",
        "\n",
        "    print(f\"Processando o vídeo do segundo {start_time_sec} ao {end_time_sec}...\")\n",
        "\n",
        "    # Converte o tempo de fim de segundos para milissegundos\n",
        "    end_time_ms = end_time_sec * 1000\n",
        "\n",
        "    try:\n",
        "        # Loop principal para processar o vídeo frame por frame\n",
        "        while True:\n",
        "            # Lê um novo frame do vídeo e uma variável de retorno (ret)\n",
        "            ret, frame = cap.read()\n",
        "\n",
        "            # Condição para parar o loop:\n",
        "            # 1. Se 'ret' for False (vídeo terminou ou erro na leitura)\n",
        "            # 2. Se a posição atual do vídeo for maior ou igual ao tempo de fim\n",
        "            if not ret or cap.get(cv2.CAP_PROP_POS_MSEC) >= end_time_ms:\n",
        "                print(f\"Processamento parado. O tempo limite de {end_time_sec} segundos foi atingido ou o vídeo terminou.\")\n",
        "                break\n",
        "\n",
        "            # Realiza a detecção de objetos no frame atual\n",
        "            results = model(frame)\n",
        "            # Extrai os resultados das detecções para um DataFrame do Pandas\n",
        "            detections = results.pandas().xyxy[0]\n",
        "\n",
        "            # --- Lógica para o Log e Persistência de Dados ---\n",
        "            # Conta o número de motos detectadas no frame\n",
        "            num_motos = len(detections)\n",
        "            # Calcula a confiança média das detecções, se houver motos\n",
        "            if num_motos > 0:\n",
        "                avg_confidence = detections['confidence'].mean()\n",
        "            else:\n",
        "                avg_confidence = 0\n",
        "\n",
        "            # Cria uma entrada de log com timestamp, contagem e confiança\n",
        "            log_entry = {\n",
        "                'timestamp': datetime.datetime.now().isoformat(),\n",
        "                'num_motos_detectadas': num_motos,\n",
        "                'confianca_media': avg_confidence\n",
        "            }\n",
        "            # Adiciona a entrada à lista de log\n",
        "            detections_log.append(log_entry)\n",
        "\n",
        "            # --- Lógica para o Output Visual ---\n",
        "            # Loop para desenhar as caixas delimitadoras para cada moto detectada\n",
        "            for _, detection in detections.iterrows():\n",
        "                # Extrai as coordenadas da caixa e a confiança\n",
        "                xmin, ymin, xmax, ymax = int(detection['xmin']), int(detection['ymin']), int(detection['xmax']), int(detection['ymax'])\n",
        "                confidence = detection['confidence']\n",
        "\n",
        "                # Desenha o retângulo verde ao redor da moto\n",
        "                cv2.rectangle(frame, (xmin, ymin), (xmax, ymax), (0, 255, 0), 2)\n",
        "                # Cria o texto com a pontuação de confiança\n",
        "                text = f\"Moto: {confidence:.2f}\"\n",
        "                # Adiciona o texto acima da caixa\n",
        "                cv2.putText(frame, text, (xmin, ymin - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (0, 255, 0), 2)\n",
        "\n",
        "            # Exibe o frame processado no ambiente do Google Colab\n",
        "            cv2_imshow(frame)\n",
        "\n",
        "    except Exception as e:\n",
        "        print(f\"Ocorreu um erro: {e}\")\n",
        "\n",
        "# Libera o objeto de captura de vídeo\n",
        "cap.release()\n",
        "\n",
        "# --- Salva o Log de Detecções em um Arquivo CSV ---\n",
        "# Verifica se a lista de log não está vazia antes de salvar\n",
        "if detections_log:\n",
        "    df_log = pd.DataFrame(detections_log)\n",
        "    df_log.to_csv('historico_deteccoes.csv', index=False)\n",
        "    print(\"\\nHistórico de detecções salvo como 'historico_deteccoes.csv'\")\n",
        "\n",
        "print(\"\\nProcessamento concluído.\")"
      ],
      "metadata": {
        "id": "tXSNwddGS0XX"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "df_log = pd.read_csv('historico_deteccoes.csv')\n",
        "\n",
        "print(df_log)"
      ],
      "metadata": {
        "id": "XsY_p67US3c_"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}